version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: zalo_ute_postgres
    environment:
      POSTGRES_DB: ZaloUTE_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5477:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
